app/views/auth.py
""" Authentication endpoints and functions """
import uuid
import re
import requests
from peewee import fn
from flask import (
    Blueprint,
    request,
    redirect,
    abort,
    url_for,
    flash,
    jsonify,
)
from flask_login import current_user, login_user, login_required
from flask_babel import _
from .. import misc
from ..config import config
from ..misc import gevent_required
from ..misc import ratelimit, AUTH_LIMIT
from ..models import User, UserStatus, rconn

bp = Blueprint("auth", __name__)


def sanitize_serv(serv):
    serv = serv.replace("%253A", "%3A")
    return serv.replace("%252F", "%2F")


def generate_cas_token(uid):
    # Create Session Ticket and store it in Redis
    token = str(uuid.uuid4())
    rconn.setex(name="cas-" + token, value=uid, time=30)
    return token


def handle_cas_ok(uid):
    # 2 - Send the ticket over to `service` with the ticket parameter
    return redirect(
        sanitize_serv(request.args.get("service"))
        + "&ticket="
        + generate_cas_token(uid)
    )


@bp.route("/proxyValidate", methods=["GET"])
@ratelimit(AUTH_LIMIT)
def sso_proxy_validate():
    if not request.args.get("ticket") or not request.args.get("service"):
        abort(400)

    pipe = rconn.pipeline()
    pipe.get("cas-" + request.args.get("ticket"))
    pipe.delete("cas-" + request.args.get("ticket"))
    red_c = pipe.execute()

    if red_c:
        try:
            user = User.get((User.uid == red_c[0].decode()) & (User.status << (0, 100)))
        except User.DoesNotExist:
            return (
                "<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>"
                '<cas:authenticationFailure code="INVALID_TICKET">'
                + _("User not found or invalid ticket")
                + "</cas:authenticationFailure></cas:serviceResponse>",
                401,
            )

        return (
            "<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>"
            f"<cas:authenticationSuccess><cas:user>{user.name.lower()}</cas:user>"
            "</cas:authenticationSuccess></cas:serviceResponse>",
            200,
        )
    else:
        return (
            "<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>"
            '<cas:authenticationFailure code="INVALID_TICKET">'
            + _("User not found or invalid ticket")
            + "</cas:authenticationFailure></cas:serviceResponse>",
            401,
        )


@bp.route("/login/with-token/<token>")
def login_with_token(token):
    flash(_("The link you used is invalid or has expired."), "error")
    return redirect(url_for("home.index"))


@bp.route("/login")
def login():
    """This exists for the url-for call in flask-login, which wants
    something.  Configure your load balancer to send this route
    to ovarit-auth."""
    abort(404)


@bp.route("/login_test_only/<name>", methods=["POST"])
def test_login(name):
    """Test-only login route"""
    if not config.app.testing:
        abort(403)

    if current_user.is_authenticated:
        abort(400)

    try:
        user = User.get(fn.Lower(User.name) == name.lower())
    except User.DoesNotExist:
        abort(403)

    if user.status != UserStatus.OK:
        abort(403)

    theuser = misc.load_user(user.uid)
    login_user(theuser, remember=False)

    return jsonify(status="OK"), 200


@bp.route("/auth/matrix", methods=["POST"])
@gevent_required  # Makes request from Matrix server.
@login_required
def get_ticket():
    """Returns a CAS ticket for the current user"""
    token = generate_cas_token(current_user.uid)
    # Not using safe_requests since we're supposed to trust this server.
    uri = f"{config.matrix.homeserver}/_matrix/client/r0/login/cas/ticket?redirectUrl=throat%3A%2F%2F&ticket={token}"
    resp = requests.get(uri, allow_redirects=False)

    if resp.status_code == 200:
        matches = re.search(r"href=\".+\?loginToken=(.+)\" class=.+?>", resp.text)
        return jsonify(token=matches.groups()[0])

    return jsonify(error="absolutely"), 400

app/views/site.py
""" Miscellaneous site endpoints """
from peewee import SQL
from flask import Blueprint, redirect, url_for, abort
from flask_login import login_required, current_user
from .. import misc
from ..models import SiteLog, SubPost, SubLog, Sub, SubPostComment
from ..misc import engine
from ..config import config

bp = Blueprint("site", __name__)


@bp.route("/chat")
@login_required
def chat():
    if config.matrix.enabled:
        return redirect(config.matrix.webchat_url)
    if config.site.enable_chat:
        return engine.get_template("chat.html").render(
            {"subOfTheDay": misc.getSubOfTheDay(), "changeLog": misc.getChangelog()}
        )
    else:
        abort(404)


@bp.route("/sitelog", defaults={"page": 1})
@bp.route("/sitelog/<int:page>")
@login_required
def view_sitelog(page):
    """Here we can see a log of admin activity on the site"""

    if not config.site.sitelog_public and not current_user.can_admin:
        abort(404)

    s1 = SiteLog.select(
        SiteLog.time,
        SiteLog.action,
        SiteLog.desc,
        SiteLog.link,
        SiteLog.uid,
        SQL("'' as sub"),
        SiteLog.target,
    )
    s2 = SubLog.select(
        SubLog.time,
        SubLog.action,
        SubLog.desc,
        SubLog.link,
        SubLog.uid,
        Sub.name.alias("sub"),
        SubLog.target,
    )
    s2 = s2.join(Sub).where(SubLog.admin)
    logs = s1 | s2
    logs = logs.order_by(logs.c.time.desc()).paginate(page, 50)

    return engine.get_template("site/log.html").render({"logs": logs, "page": page})


@bp.route("/p/<pid>")
def view_post_inbox(pid):
    """Gets route to post from just pid"""
    try:
        post = SubPost.get(SubPost.pid == pid)
    except SubPost.DoesNotExist:
        return abort(404)
    return redirect(url_for("sub.view_post", sub=post.sid.name, pid=post.pid))


@bp.route("/c/<cid>")
def view_comment_inbox(cid):
    """Gets route to post from just cid"""
    try:
        comm = SubPostComment.get(SubPostComment.cid == cid)
    except SubPostComment.DoesNotExist:
        return abort(404)
    return redirect(
        url_for("sub.view_perm", sub=comm.pid.sid.name, pid=comm.pid_id, cid=comm.cid)
    )


@bp.route("/activity")
def view_activity():
    return engine.get_template("site/activity.html").render(
        {
            # 'page': page,
            "subOfTheDay": misc.getSubOfTheDay(),
            "changeLog": misc.getChangelog(),
            "activity": misc.recent_activity(False),
        }
    )

app/views/sub.py
""" All endpoints related to stuff done inside of a particular sub """
import datetime
from flask import Blueprint, redirect, url_for, abort, request, Response
from flask_login import login_required, current_user
from feedgen.feed import FeedGenerator
from peewee import fn, JOIN
from ..config import config
from ..misc import engine, limit_pagination
from ..models import (
    Sub,
    SubMetadata,
    SubLog,
    User,
    SubMod,
    SubBan,
    SubUserFlairChoice,
)
from ..forms import (
    EditSubFlair,
    EditSubForm,
    EditMod2Form,
    BanUserSubForm,
    CreateSubFlair,
    AssignSubUserFlair,
)
from .. import misc


blueprint = Blueprint("sub", __name__)


@blueprint.route("/<sub>/")
@blueprint.route("/<sub>")
def view_sub(sub):
    """Here we can view subs"""
    if sub.lower() == "all":
        return redirect(url_for("home.all_hot", page=1))

    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    try:
        x = SubMetadata.select().where(SubMetadata.sid == sub.sid)
        x = x.where(SubMetadata.key == "sort").get()
        x = x.value
    except SubMetadata.DoesNotExist:
        x = "v"
    if x == "v_two":
        return redirect(url_for("sub.view_sub_new", sub=sub.name))
    elif x == "v_three":
        return redirect(url_for("sub.view_sub_top", sub=sub.name))
    else:
        return redirect(url_for("sub.view_sub_hot", sub=sub.name))


@blueprint.route("/<sub>/edit/flairs")
@login_required
def edit_sub_flairs(sub):
    # Implemented by the modmail server.  This stub exists for use by url_for.
    abort(404)


@blueprint.route("/<sub>/edit/user_flairs")
@login_required
def edit_sub_user_flairs(sub):
    """Here we manage user flairs"""
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    flairs = SubUserFlairChoice.select().where(SubUserFlairChoice.sub == sub.sid)
    # assigned_flairs = SubUserFlair.select(SubUserFlair.flair_choice, SubUserFlair.flair, User.name)\
    #     .join(User).where(SubUserFlair.sub == sub.sid).dicts()

    assignflair = AssignSubUserFlair()

    formflairs = []
    for flair in flairs:
        formflairs.append(EditSubFlair(flair=flair.id, text=flair.flair))
        assignflair.flair_id.choices.append((flair.id, flair.flair))

    # formuserflairs = []
    # for flair in assigned_flairs:
    #     formuserflairs.append(EditSubUserFlair(flair=flair['flair_choice'], text=flair['flair'], user=flair['name']))

    return engine.get_template("sub/user_flairs.html").render(
        {
            "sub": sub,
            "flairs": formflairs,
            "createflair": CreateSubFlair(),  # 'assigned_flairs': formuserflairs,
            "assignflair": assignflair,
        }
    )


@blueprint.route("/<sub>/edit/rules")
@login_required
def edit_sub_rules(sub):
    # Implemented by the modmail server.  This stub exists for use by url_for.
    abort(404)


@blueprint.route("/<sub>/edit")
@login_required
def edit_sub(sub):
    """Here we can edit sub info and settings"""
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 1) or current_user.is_admin():
        submeta = misc.metadata_to_dict(
            SubMetadata.select().where(SubMetadata.sid == sub.sid)
        )
        form = EditSubForm()
        # pre-populate the form.
        form.subsort.data = submeta.get("sort")
        form.sidebar.data = sub.sidebar
        form.title.data = sub.title

        return engine.get_template("sub/settings.html").render(
            {"sub": sub, "editsubform": form, "metadata": submeta}
        )
    else:
        abort(403)


@blueprint.route("/<sub>/sublog", defaults={"page": 1})
@blueprint.route("/<sub>/sublog/<int:page>")
def view_sublog(sub, page):
    """Here we can see a log of mod/admin activity in the sub"""
    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    subInfo = misc.getSubData(sub["sid"])
    if not config.site.force_sublog_public:
        log_is_private = subInfo.get("sublog_private", 0) == "1"

        if log_is_private and not (
            current_user.is_mod(sub["sid"], 1) or current_user.is_admin()
        ):
            abort(404)

    subMods = misc.getSubMods(sub["sid"])
    logs = (
        SubLog.select()
        .where(SubLog.sid == sub["sid"])
        .order_by(SubLog.lid.desc())
        .paginate(page, 50)
    )
    return engine.get_template("sub/log.html").render(
        {"sub": sub, "logs": logs, "page": page, "subInfo": subInfo, "subMods": subMods}
    )


@blueprint.route("/<sub>/mods")
@login_required
def edit_sub_mods(sub):
    """Here we can edit moderators for a sub"""
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if (
        current_user.is_mod(sub.sid, 2)
        or current_user.is_modinv(sub.sid)
        or current_user.is_admin()
    ):
        subdata = misc.getSubData(sub.sid, extra=True)
        subMods = misc.getSubMods(sub.sid)
        modInvites = (
            SubMod.select(User.name, SubMod.power_level)
            .join(User)
            .where((SubMod.sid == sub.sid) & SubMod.invite)
        )
        return engine.get_template("sub/mods.html").render(
            {
                "sub": sub,
                "subdata": subdata,
                "editmod2form": EditMod2Form(),
                "subMods": subMods,
                "subModInvites": modInvites,
            }
        )
    else:
        abort(403)


@blueprint.route("/<sub>/new.rss")
def sub_new_rss(sub):
    """RSS feed for /sub/new"""
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    fg = FeedGenerator()
    fg.id(request.url)
    fg.title("New posts from " + sub.name)
    fg.link(href=request.url_root, rel="alternate")
    fg.link(href=request.url, rel="self")

    posts = misc.getPostList(
        misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub.sid)
    )["posts"]

    return Response(
        misc.populate_feed(fg, posts).atom_str(pretty=True),
        mimetype="application/atom+xml",
    )


@blueprint.route("/<sub>/new", defaults={"page": None})
@blueprint.route("/<sub>/new/<int:page>")
@limit_pagination
def view_sub_new(sub, page):
    """The index page, all posts sorted as most recent posted first"""
    if sub.lower() == "all":
        return redirect(url_for("home.all_new"))

    flair = request.args.get("flair")

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    isSubMod = current_user.is_mod(sub["sid"], 1) or current_user.is_admin()

    page_info = misc.getPostList(
        misc.postListQueryBase(
            noAllFilter=True, isSubMod=isSubMod, flair=flair, sort="new"
        ).where(Sub.sid == sub["sid"]),
        sort="new",
        page=page,
        first=request.args.get("first"),
        after=request.args.get("after"),
        last=request.args.get("last"),
        before=request.args.get("before"),
        include_mod_counts=isSubMod,
    )

    return engine.get_template("sub.html").render(
        {
            "sub": sub,
            "subInfo": misc.getSubData(sub["sid"]),
            "isSubMod": isSubMod,
            "page_info": page_info,
            "route": "sub.view_sub_new",
            "subMods": misc.getSubMods(sub["sid"]),
            "flair": flair,
        }
    )


@blueprint.route("/<sub>/bannedusers")
def view_sub_bans(sub):
    """See banned users for the sub"""
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    subInfo = misc.getSubData(sub.sid)
    if not config.site.force_sublog_public:
        banned_users_is_private = subInfo.get("sub_banned_users_private", 0) == "1"

        if banned_users_is_private and not (
            current_user.is_mod(sub.sid, 1) or current_user.is_admin()
        ):
            abort(404)

    user = User.alias()
    created_by = User.alias()
    banned = SubBan.select(
        user, created_by, SubBan.created, SubBan.reason, SubBan.expires
    )
    banned = (
        banned.join(user, on=SubBan.uid)
        .switch(SubBan)
        .join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    )
    banned = (
        banned.where(SubBan.sid == sub.sid)
        .where(SubBan.effective)
        .where(
            (SubBan.expires.is_null(True))
            | (SubBan.expires > datetime.datetime.utcnow())
        )
    )
    banned = banned.order_by(SubBan.created.is_null(True), SubBan.created.desc())

    xbans = SubBan.select(
        user, created_by, SubBan.created, SubBan.reason, SubBan.expires
    )
    xbans = (
        xbans.join(user, on=SubBan.uid)
        .switch(SubBan)
        .join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    )

    xbans = xbans.where(SubBan.sid == sub.sid)
    xbans = xbans.where(
        (~SubBan.effective)
        | (
            (SubBan.expires.is_null(False))
            & (SubBan.expires < datetime.datetime.utcnow())
        )
    )
    xbans = xbans.order_by(
        SubBan.created.is_null(True), SubBan.created.desc(), SubBan.expires.asc()
    )

    return engine.get_template("sub/bans.html").render(
        {
            "sub": sub,
            "banned": banned,
            "xbans": xbans,
            "banuserform": BanUserSubForm(),
            "submods": misc.getSubMods(sub.sid),
        }
    )


@blueprint.route("/<sub>/top", defaults={"page": None})
@blueprint.route("/<sub>/top/<int:page>")
@limit_pagination
def view_sub_top(sub, page):
    """The index page, /top sorting"""
    if sub.lower() == "all":

app/templates/indexpost.html
<div pid="{{post.pid}}" class="{% if post.deleted != 0 %}deletedpost {% endif %}post">
    <div class="misctainer">
      <div class="votebuttons">
        {% if post.userstatus != 10 and not func.is_archived(post) %}
        <div title="Upvote" class="upvote{%if post.positive == 1%} upvoted{%endif%}" data-pid="{{post.pid}}" data-icon="upvote"></div>
        <div class="score">{{post.score}}</div>
        <div title="Downvote" class="downvote{%if post.positive == 0%} downvoted{%endif%}" data-pid="{{post.pid}}" data-icon="downvote"></div>
        {%endif%}
      </div>
      <div class="thcontainer">
        <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">
          <div class="thumbnail">
            {% if post.link != None %}
              {% if post.thumbnail == '' %}
                <span class="placeholder" data-icon="link"></span>
              {% elif post.thumbnail == 'deferred' %}
                <span class="placeholder deferred {{ post.blur }}" data-icon="link"
                      data-deferred="SubPost-{{ post.pid }}"></span>
              {% else %}
                <img class="lazy {{ post.blur }}" src="{{ url_for('static', filename='img/1x1.gif') }}"
                     data-src="{{ thumbnail_url(post.thumbnail) }}"/>
              {%endif %}
            {%else%}
              <span class="placeholder" data-icon="chat"></span>
            {% endif%}

          </div>
        </a>
      </div>
    </div>
    <div class="pbody">
      <div class="post-heading">
        {% if post.nsfw %}
        <div class="nsfw" alt="Not safe for work">{{_('NSFW')}}</div>
        {%endif%}
        {% if post.flair %}
          <a class="postflair" href="{{url_for('sub.view_sub_hot', sub=post.sub, flair=post.flair)}}">{{post.flair}}</a>
        {% endif %}
        {% if post.link == None %}
          <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">
          {% if post.deleted == 1 %}
            {{_('[Deleted by User]')}}
          {% elif post.deleted in [2, 3] %}
            {{_('[Deleted by Mod or Admin]')}}
          {% endif %}
          <span class="{{ post.blur }}">{{post.title}}</span>
        </a>
        {% else %}
          {% if post.link.startswith('http:') %}<span title="not https" class="p-icon" data-icon="exclaim"></span>{% endif %}
          <a rel="noopener nofollow ugc" target="_blank" href="{{post.link}}" class="title">
            {% if post.deleted == 1 %}
              {{_('[Deleted by User]')}}
            {% elif post.deleted in [2, 3] %}
              {{_('[Deleted by Mod or Admin]')}}
            {% endif %}
            <span class="{{ post.blur }}">{{post.title}}</span>
          </a>
          <a href="{{url_for('home.all_domain_new', domain=func.getDomain(post.link), page=1)}}" class="domain">({{func.getDomain(post.link)}})</a>
        {% endif %}
      </div>
      <div class="author">
          {% if post.link %}
            {% if func.getDomain(post.link) in config.site.expando_sites %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% elif func.isImage(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="image"></div></div>
            {% elif func.isVideo(post.link) or func.isGifv(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% endif %}
          {% elif post.content != '' %}
          <div class="expando" data-pid="{{post.pid}}" data-t="txt" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="text"></div></div>
          {% endif %}
        posted <relative-time datetime="{{post.posted.isoformat()}}Z"></relative-time> by
        {% if post.userstatus != 10 %}
          <a class="authorlink" href="{{url_for('user.view', user=post.user)}}">{{post.user}}</a>
        {% endif %}
        {% if sub and post.pid in func.getStickyPid(sub.sid) %}
        - <span class="stick">sticky</span>
        {% endif %}
        {% if not sub %} on
        <a href="{{url_for('sub.view_sub', sub=post.sub)}}">{{post.sub}}</a>
        {%endif%}
      </div>
      <div class="links">
        <a class="comments" href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}">comments {%if post.comments>0%}({{post.comments}}){%endif%}</a>
      </div>
    </div>
</div>

app/templates/subs.html
{% extends "layout.html" %}
{% block title %}Subs | {{config.site.lema}}{% endblock %}
{% block navbar %}

<ul class="right">
  <li class="large">Subs</li>
</ul>
{% endblock %}

{% block sidebar %}
<div>
  <form class="pure-g search" action="{{ url_for('do.search', stype='home.subs') }}" method="post">
    <div class="icon" data-icon="search"> </div>
    <input name="term" placeholder="Search sub name..." type="search" class="pure-u-1" value="{{term}}">
  </form>
</div>
<hr>
{{ super() }}
{% endblock %}

{% block content %}
{{ super() }}
{% if not subs %}<h1 class="noshit">There are no subs here, yet.</h1>{% endif %}
<div id="center-container">
  <div class="subs content">
    <table class="sortable pure-table" >
      <thead>
        <tr>
          <th>
            {% if sort == 'name_asc' %}
              <a href="{{cp_uri}}/name_desc">Sub Name <span class="tx-icon" data-icon="downvote"></span></a>
            {%elif sort == 'name_desc' %}
              <a href="{{cp_uri}}/name_asc">Sub Name <span class="tx-icon" data-icon="upvote"></span></a>
            {%else%}
              <a href="{{cp_uri}}/name_asc">Sub Name <span class="tx-icon" data-icon="updown"></span></a>
            {%endif %}
            </th>
          <th>Created</th>
          <th>
            {% if sort == 'subs_asc' %}
              <a href="{{cp_uri}}/subs_desc">Subscribers <span class="tx-icon" data-icon="downvote"></span></a>
            {%elif sort == 'subs_desc' %}
              <a href="{{cp_uri}}/subs_asc">Subscribers <span class="tx-icon" data-icon="upvote"></span></a>
            {%else%}
            <a href="{{cp_uri}}/subs_desc">Subscribers <span class="i-icon" data-icon="updown"></span></a>
            {%endif %}
          </th>
          <th>
            {% if sort == 'posts_asc' %}
              <a href="{{cp_uri}}/posts_desc">Posts <span class="tx-icon" data-icon="downvote"></span></a>
            {%elif sort == 'posts_desc' %}
              <a href="{{cp_uri}}/posts_asc">Posts <span class="tx-icon" data-icon="upvote"></span></a>
            {%else%}
              <a href="{{cp_uri}}/posts_desc">Posts <span class="i-icon" data-icon="updown"></span></a>
            {%endif %}
          </th>
        </tr>
      </thead>
      <tbody>
        {% for sub in subs %}
        <tr>
          <td  class="subsentry{% if current_user.has_subscribed(sub.name) %} subsubscribed{% endif %}{% if current_user.has_blocked(sub.sid) %} blocked{% endif %}" data-sid="{{sub.sid}}">
            <div class="subname" title="{{sub.title}}">
              {% if sub.nsfw  %}<span style="color:white;background:red">nsfw</span>{% endif %}
              <a href="{{url_for('sub.view_sub', sub=sub.name)}}">{{sub.name}}</a>
            </div>
          </td>
          <td><relative-time datetime="{{sub.creation}}" prefix=""></relative-time></td>
          <td>
            <div role="group" class="pure-button-group" data-sid="{{sub.sid}}" style="display:inline-block;">

              {% if current_user.has_subscribed(sub.name) %}
                <button data-ac="unsubscribe" class="sub pure-button button-xsmall" style="display:inline-block; width: 8em;"><span class="sbm-icon" data-icon="check"></span>Subscribed</button>
              {% elif current_user.has_blocked(sub.sid) %}
                <button data-ac="unblock" class="blk button-warning pure-button button-xsmall" style="display:inline-block; width: 8em;"><span class="sbm-icon" data-icon="block"></span>Blocked</button>
              {%else%}
                <button data-ac="subscribe" class="unsub pure-button button-xsmall" style="display:inline-block; width: 8em;"><span class="sbm-icon" data-icon="add"></span>Subscribe</button>
              {%endif%}
            </div>
            <span style="margin-left: .3em;">{{sub.subscribers}}</span>

          </td>
          <td>{{sub.posts}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{%if nav=='home.subs_search'%}
  <div class="col-12">
    {% if page > 1 %}
    <a href="{{url_for(nav, term=term, page=(page-1))}}" class="pure-button">prev</a>
    {% endif %}
    {% if subs|length == 50 %}
    <a href="{{url_for(nav,term=term, page=(page+1))}}" class="pure-button">next</a>
    {% endif %}
  </div>
{% else %}
  <div class="col-12">
    {% if page > 1 %}
    <a href="{{url_for(nav, page=(page-1))}}" class="pure-button">prev</a>
    {% endif %}
    {% if subs|length == 50 %}
    <a href="{{url_for(nav, page=(page+1))}}" class="pure-button">next</a>
    {% endif %}
  </div>
{% endif %}
{% endblock %}